# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Bookingpad
email: contact@bookingpad.net

description: >- # this means to ignore newlines until "baseurl:"
  Bookingpad is the most advanced NDC-ready booking tool for travel agents.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bookingpad.net"
twitter_username: Bookingpad
github_username:  AirGateway

include:
  - _redirects

permalink: /:year-:month-:day/:title
paginate: 5

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

collections:
  posts:
    permalink: "/:collection/:path/"
    output: true
    layout: "post"
  faqs:
    permalink: "/:collection/:path/"
    output: true
    layout: "post"
  gallery:
    output: false
  features:
    output: true
    permalink: "/:collection/:path/"
  plans:
    output: false
    order:
      - basic.md
      - pro.md
      - business.md
  customers:
    output: false
  partners:
    output: false
  airlines:
    output: false
  providers:
    output: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
